### ISSUE TITLE
不能是使用了

### ISSUE THREAD

**Issue by L1cardo** [fq050766/qq-music-list-to-kwl#1]
如图，怎么解决
能不能写一个教程，不太会使用
![image](https://user-images.githubusercontent.com/33802186/34379164-c2559ada-eb34-11e7-878c-f17865e5ad7d.png)

**Comment by fengqiangboy** [comment]
不是用这个终端，用Windows自带的终端就行了。按住`win+r`,然后输入`cmd`，打开就是终端了
