### ISSUE TITLE
语句错误

### ISSUE THREAD

**Issue by dnslin** [fq050766/qq-music-list-to-kwl#4]
soup = BeautifulSoup(html.text, "html5lib") 
这条语句有误会出现 
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib.  Do you need to install a parser library? 
所以我将上述语句修改成 
soup = BeautifulSoup(html.text, "html.parser") 
成功运行但是导出歌单为0

**Comment by fengqiangboy** [comment]
现在好像失效了，歌单结构改了
